scUser: bamilo2_bi
scPw: ==47.scale.ACTUALLY.start.62==
scHost: rr-4xon5d7xscl6ucvq0yo.mysql.germany.rds.aliyuncs.com
scDb: sc_live_ir
omsUser: thomas
omsPw: TH#)dec@)!&
omsHost: 178.22.70.43:3306
omsDb: oms_live_ir