title: Sellers penalties
body: Please find enclosed the sellers penalties
attachPath: seller_mistake_penalty.csv
recipient: thomas.beaudouin@bamilo.com
senderEmail: bamilo.automation@zoho.com
senderName: bamilo.automation
senderPw: golangisgreat
smtpAddr: smtp.zoho.com
smtpPort: 587